sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t harshitbangar/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true harshitbangar/docker-react npm run test